### ISSUE TITLE
Append a summary `$GITHUB_STEP_SUMMARY`

### ISSUE THREAD

**Issue by kraenhansen** [daniellockyer/mocha-github-actions-reporter#15]
I find myself scrolling to the end of the step to get to the "epilogue":

```
  816 passing (8m)
  79 pending
  2 failing
```

I think it would be great if this was written to the [`$GITHUB_STEP_SUMMARY`](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary) file when the run ends, this way users can get an idea of the state of the tests just by looking at the run overview page.

**Comment by daniellockyer** [comment]
Fixed by https://github.com/daniellockyer/mocha-github-actions-reporter/pull/16
