### ISSUE TITLE
Update NPM version

### ISSUE THREAD

**Issue by cah-dunn** [daniellockyer/mocha-github-actions-reporter#6]
Thanks for providing this package - it was exactly what I needed and worked seamlessly.

Would it be possible to update the NPM package with the latest version (which patches the vulnerability in `@actions/core`)?

**Comment by daniellockyer** [comment]
Hey @cah-dunn! Thanks for the issue. I've just released 0.2.2 which contains this bump :slightly_smiling_face:

**Comment by cah-dunn** [comment]
Great, thank you @daniellockyer
